spring.application.name=bio_new

###################### Server Configuration ######################
server.address=192.168.1.109
server.port=8081

###################### Postgres database ######################
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.url=jdbc:postgresql://localhost:5432/simcaf
#spring.datasource.url=jdbc:postgresql://3.67.135.35:5432/scms
#spring.datasource.url=jdbc:postgresql://3.76.28.3:5432/scms
spring.datasource.username=simcaf
spring.datasource.password=simcaf@2025

###################### JPA/Hibernate Configuration ######################
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

###################### Thymeleaf Configuration ######################
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

###################### ZKTeco Device Configuration ######################
zkteco.default.device.ip=192.168.1.127
zkteco.default.device.port=4370
zkteco.sync.enabled=true
zkteco.sync.interval=60000

