spring.application.name=bio_new

###################### Postgres database ######################
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.url=jdbc:postgresql://localhost:5432/simcaf
#spring.datasource.url=jdbc:postgresql://3.67.135.35:5432/scms
#spring.datasource.url=jdbc:postgresql://3.76.28.3:5432/scms
spring.datasource.username=simcaf
spring.datasource.password=simcaf@2025

